// Exposes constants provided by native layer.

import {NativeModules} from 'react-native';

declare global {
  var __turboModuleProxy: object | undefined;
}

const ReactNativeAudio = global.__turboModuleProxy
  ? require('./NativeAudio').default
  : NativeModules.Audio;

const {
  AUDIO_FORMAT_PCM_8BIT,
  AUDIO_FORMAT_PCM_16BIT,
  AUDIO_FORMAT_PCM_FLOAT,

  AUDIO_SOURCE_CAMCODER,
  AUDIO_SOURCE_DEFAULT,
  AUDIO_SOURCE_MIC,
  AUDIO_SOURCE_REMOTE_SUBMIX,
  AUDIO_SOURCE_UNPROCESSED,
  AUDIO_SOURCE_VOICE_CALL,
  AUDIO_SOURCE_VOICE_COMMUNICATION,
  AUDIO_SOURCE_VOICE_DOWNLINK,
  AUDIO_SOURCE_VOICE_PERFORMANCE,
  AUDIO_SOURCE_VOICE_RECOGNITION,
  AUDIO_SOURCE_VOICE_UPLINK,

  CHANNEL_IN_MONO,
  CHANNEL_IN_STEREO,
} = ReactNativeAudio.getConstants();

export enum AUDIO_FORMATS {
  PCM_8BIT = AUDIO_FORMAT_PCM_8BIT,
  PCM_16BIT = AUDIO_FORMAT_PCM_16BIT,
  PCM_FLOAT = AUDIO_FORMAT_PCM_FLOAT,
}

export enum AUDIO_SOURCES {
  CAMCODER = AUDIO_SOURCE_CAMCODER,
  DEFAULT = AUDIO_SOURCE_DEFAULT,
  MIC = AUDIO_SOURCE_MIC,
  REMOTE_SUBMIX = AUDIO_SOURCE_REMOTE_SUBMIX,
  RAW = AUDIO_SOURCE_UNPROCESSED,
  VOICE_CALL = AUDIO_SOURCE_VOICE_CALL,
  VOICE_COMMUNICATION = AUDIO_SOURCE_VOICE_COMMUNICATION,
  VOICE_DOWNLINK = AUDIO_SOURCE_VOICE_DOWNLINK,
  VOICE_PERFORMANCE = AUDIO_SOURCE_VOICE_PERFORMANCE,
  VOICE_RECOGNITION = AUDIO_SOURCE_VOICE_RECOGNITION,
  VOICE_UPLINK = AUDIO_SOURCE_VOICE_UPLINK,
}

export enum CHANNEL_CONFIGS {
  MONO = CHANNEL_IN_MONO,
  STEREO = CHANNEL_IN_STEREO,
}
